const BIRTHDAY_DATA = [
  {
    month: "1",
    date: "1",
    flower: "스노우드롭",
    f_mean: "희망",
    stone: "임페리얼 제이드",
    s_mean: "불로불사",
  },
  {
    month: "1",
    date: "2",
    flower: "노랑수선화",
    f_mean: "사랑에 답하여",
    stone: "랜드스케이프 아게이트",
    s_mean: "불행을 막아줌",
  },
  {
    month: "1",
    date: "3",
    flower: "사프란",
    f_mean: "후회없는 청춘",
    stone: "토패저라이트",
    s_mean: "좋은 소식",
  },
  {
    month: "1",
    date: "4",
    flower: "히아신스",
    f_mean: "차분한 사랑",
    stone: "크리소콜라",
    s_mean: "정신의 안정",
  },
  {
    month: "1",
    date: "5",
    flower: "노루귀",
    f_mean: "인내",
    stone: "골든 지르콘",
    s_mean: "슬픔과 의혹의 제거",
  },
  {
    month: "1",
    date: "6",
    flower: "흰색 제비꽃",
    f_mean: "순진무구한 사랑",
    stone: "스타 가넷",
    s_mean: "성스러운 실행력",
  },
  {
    month: "1",
    date: "7",
    flower: "튤립",
    f_mean: "실연",
    stone: "암모라이트",
    s_mean: "과거의 추억",
  },
  {
    month: "1",
    date: "8",
    flower: "보랏빛 제비꽃",
    f_mean: "사랑",
    stone: "크롬 토르마린",
    s_mean: "내면의 증강",
  },
  {
    month: "1",
    date: "9",
    flower: "노란색 제비꽃",
    f_mean: "수줍은 사랑",
    stone: "하이드로 그로슐라라이트",
    s_mean: "사랑의 달성",
  },
  {
    month: "1",
    date: "10",
    flower: "회양목",
    f_mean: "참고 견뎌냄",
    stone: "골드",
    s_mean: "확실한 조언과 힘",
  },
  {
    month: "1",
    date: "11",
    flower: "측백나무",
    f_mean: "견고한 우정",
    stone: "스페큘러 라이트",
    s_mean: "자기인식",
  },
  {
    month: "1",
    date: "12",
    flower: "향기 알리섬",
    f_mean: "빼어난 미모",
    stone: "옵시디언",
    s_mean: "잡념의 제거",
  },
  {
    month: "1",
    date: "13",
    flower: "수선화",
    f_mean: "신비",
    stone: "파울러라이트",
    s_mean: "맺어지는 사랑",
  },
  {
    month: "1",
    date: "14",
    flower: "시클라멘",
    f_mean: "내성적 성격",
    stone: "프레쉬 워터 펄",
    s_mean: "조화로운 애정",
  },
  {
    month: "1",
    date: "15",
    flower: "가시",
    f_mean: "엄격",
    stone: "피죤 블러드",
    s_mean: "불멸",
  },
  {
    month: "1",
    date: "16",
    flower: "노랑 히아신스",
    f_mean: "승부",
    stone: "블루문 스톤",
    s_mean: "성인의 사랑",
  },
  {
    month: "1",
    date: "17",
    flower: "수영",
    f_mean: "애정",
    stone: "안티몬",
    s_mean: "사악함으로부터의 방어",
  },
  {
    month: "1",
    date: "18",
    flower: "어저귀",
    f_mean: "억측",
    stone: "로제라이트",
    s_mean: "희망의 상징",
  },
  {
    month: "1",
    date: "19",
    flower: "소나무",
    f_mean: "불로장수",
    stone: "암블리고나이트",
    s_mean: "불멸의 힘",
  },
  {
    month: "1",
    date: "20",
    flower: "미나리아재비",
    f_mean: "천진난만",
    stone: "스노우프레이크 옵시디언",
    s_mean: "사랑의 유지",
  },
  {
    month: "1",
    date: "21",
    flower: "담쟁이덩굴",
    f_mean: "우정",
    stone: "피콕 컬러 오팔",
    s_mean: "구애의 예감",
  },
  {
    month: "1",
    date: "22",
    flower: "이끼",
    f_mean: "모성애",
    stone: "스타 베릴",
    s_mean: "은총",
  },
  {
    month: "1",
    date: "23",
    flower: "부들",
    f_mean: "순종",
    stone: "알렉잰드라이프 가넷",
    s_mean: "주야의 변모",
  },
  {
    month: "1",
    date: "24",
    flower: "가을 사프란",
    f_mean: "절도의 미",
    stone: "밀키 쿼츠",
    s_mean: "모성애",
  },
  {
    month: "1",
    date: "25",
    flower: "점나도나물",
    f_mean: "순진무구한 사랑",
    stone: "사도닉스",
    s_mean: "행복한 결혼",
  },
  {
    month: "1",
    date: "26",
    flower: "미모사",
    f_mean: "예민한 마음",
    stone: "파이롭",
    s_mean: "불같이 타오르는 마음",
  },
  {
    month: "1",
    date: "27",
    flower: "마가목",
    f_mean: "게으름을 모르는 마음",
    stone: "알만다인",
    s_mean: "실행력의 승리",
  },
  {
    month: "1",
    date: "28",
    flower: "검은 미루나무",
    f_mean: "용기",
    stone: "핑크 토파즈",
    s_mean: "지력과 체력의 회복",
  },
  {
    month: "1",
    date: "29",
    flower: "이끼",
    f_mean: "모성애",
    stone: "팬텀 크리스탈",
    s_mean: "얼음 화석",
  },
  {
    month: "1",
    date: "30",
    flower: "매쉬 메리골드",
    f_mean: "반드시 오고야 말 행복",
    stone: "파티컬러드 플로라이트",
    s_mean: "과거와 미래",
  },
  {
    month: "1",
    date: "31",
    flower: "노란 사프란",
    f_mean: "청춘의 환희",
    stone: "알렉산드라이트 캣츠아이",
    s_mean: "망설임과 선택과 변신",
  },
  {
    month: "2",
    date: "1",
    flower: "앵초",
    f_mean: "젊은 시절의 고뇌",
    stone: "유렉사이트",
    s_mean: "꿰뚫어 보는 마음",
  },
  {
    month: "2",
    date: "2",
    flower: "모과",
    f_mean: "유혹",
    stone: "콩크 펄",
    s_mean: "가장 사랑하는 사람",
  },
  {
    month: "2",
    date: "3",
    flower: "황새냉이",
    f_mean: "그대에게 바친다",
    stone: "메라나이트",
    s_mean: "투쟁과 목표의 달성",
  },
  {
    month: "2",
    date: "4",
    flower: "빨간 앵초",
    f_mean: "비할 바 없는 아름다움",
    stone: "바이컬러 아메시스트",
    s_mean: "깨달음",
  },
  {
    month: "2",
    date: "5",
    flower: "양치",
    f_mean: "사랑스러움",
    stone: "프람 스톤",
    s_mean: "난관을 이기다",
  },
  {
    month: "2",
    date: "6",
    flower: "바위솔",
    f_mean: "근면함",
    stone: "그레이 스타 사파이어",
    s_mean: "새벽에 전해진 좋은 소식",
  },
  {
    month: "2",
    date: "7",
    flower: "물망초",
    f_mean: "나를 잊지 말아요",
    stone: "컨곰",
    s_mean: "규율과 수호",
  },
  {
    month: "2",
    date: "8",
    flower: "범의귀",
    f_mean: "절실한 애정",
    stone: "루틸 레이티드 쿼츠",
    s_mean: "가정의 평화",
  },
  {
    month: "2",
    date: "9",
    flower: "은매화",
    f_mean: "사랑의 속삭임",
    stone: "레드 재스퍼",
    s_mean: "올바른 판단",
  },
  {
    month: "2",
    date: "10",
    flower: "서향",
    f_mean: "영광",
    stone: "레드 타이거 아이",
    s_mean: "운명의 파괴와 창조",
  },
  {
    month: "2",
    date: "11",
    flower: "멜리사",
    f_mean: "동정",
    stone: "워터 원",
    s_mean: "시간의 흐름",
  },
  {
    month: "2",
    date: "12",
    flower: "쥐꼬리망초",
    f_mean: "가련함",
    stone: "옐로우 스피넬",
    s_mean: "자기애",
  },
  {
    month: "2",
    date: "13",
    flower: "갈풀",
    f_mean: "끈기",
    stone: "바이컬러 플로라이트",
    s_mean: "두 얼굴의 매력",
  },
  {
    month: "2",
    date: "14",
    flower: "카모밀레",
    f_mean: "역경에 굴하지 않는 강인함",
    stone: "핑크 오팔",
    s_mean: "사랑의 만남",
  },
  {
    month: "2",
    date: "15",
    flower: "삼나무",
    f_mean: "그대를 위해 살다",
    stone: "핑크 지르콘",
    s_mean: "고통의 완화",
  },
  {
    month: "2",
    date: "16",
    flower: "월계수",
    f_mean: "명예",
    stone: "드라바이트",
    s_mean: "인생의 전개",
  },
  {
    month: "2",
    date: "17",
    flower: "야생화",
    f_mean: "친숙한 자연",
    stone: "타이거 아이언",
    s_mean: "강한 신념",
  },
  {
    month: "2",
    date: "18",
    flower: "미나리아재비",
    f_mean: "천진난만",
    stone: "오렌지 토파즈",
    s_mean: "지혜와 논리",
  },
  {
    month: "2",
    date: "19",
    flower: "떡갈나무",
    f_mean: "붙임성이 좋음",
    stone: "워트 드롭 쿼츠",
    s_mean: "생명",
  },
  {
    month: "2",
    date: "20",
    flower: "칼미아",
    f_mean: "커다란 희망",
    stone: "브라운 오닉스",
    s_mean: "정절",
  },
  {
    month: "2",
    date: "21",
    flower: "네모필라",
    f_mean: "애국심",
    stone: "혼",
    s_mean: "애타는 사랑",
  },
  {
    month: "2",
    date: "22",
    flower: "무궁화",
    f_mean: "영원",
    stone: "캣츠아이쿼츠",
    s_mean: "미래의 예감",
  },
  {
    month: "2",
    date: "23",
    flower: "살구꽃",
    f_mean: "순수한 사랑",
    stone: "체리 핑크 루비",
    s_mean: "사랑의 의혹",
  },
  {
    month: "2",
    date: "24",
    flower: "빙카",
    f_mean: "즐거운 추억",
    stone: "화이트 펄",
    s_mean: "겸양과 성의",
  },
  {
    month: "2",
    date: "25",
    flower: "사향장미",
    f_mean: "변덕스러운 사랑",
    stone: "팬텀 아메시스트",
    s_mean: "환영",
  },
  {
    month: "2",
    date: "26",
    flower: "아도니스",
    f_mean: "추억",
    stone: "골드 쿼츠",
    s_mean: "세계를 보는 눈",
  },
  {
    month: "2",
    date: "27",
    flower: "아라비아의별",
    f_mean: "순수",
    stone: "큐프라이트",
    s_mean: "다면성",
  },
  {
    month: "2",
    date: "28",
    flower: "보리",
    f_mean: "일치단결",
    stone: "카모라트 코랄",
    s_mean: "견디는 마음",
  },
  {
    month: "2",
    date: "29",
    flower: "아르메리아",
    f_mean: "배려",
    stone: "패러사이트",
    s_mean: "만물을 향한 비상",
  },
  {
    month: "3",
    date: "1",
    flower: "수선화",
    f_mean: "자존",
    stone: "플로라이트",
    s_mean: "비밀의 사랑",
  },
  {
    month: "3",
    date: "2",
    flower: "미나리아재비",
    f_mean: "아름다운 인격",
    stone: "쉘 오팔",
    s_mean: "화합",
  },
  {
    month: "3",
    date: "3",
    flower: "자운영",
    f_mean: "나의 행복",
    stone: "핑크 베릴",
    s_mean: "매력적인 배려심",
  },
  {
    month: "3",
    date: "4",
    flower: "라즈베리",
    f_mean: "애정",
    stone: "실버",
    s_mean: "젊음의 주장",
  },
  {
    month: "3",
    date: "5",
    flower: "수레국화",
    f_mean: "행복감",
    stone: "로얄 블루 사파이어",
    s_mean: "행운과 천명",
  },
  {
    month: "3",
    date: "6",
    flower: "데이지",
    f_mean: "명랑",
    stone: "코펄",
    s_mean: "정과 동",
  },
  {
    month: "3",
    date: "7",
    flower: "황새냉이",
    f_mean: "사무치는 그리움",
    stone: "아크로아이트",
    s_mean: "투명",
  },
  {
    month: "3",
    date: "8",
    flower: "밤꽃",
    f_mean: "진심",
    stone: "스미스소나이트",
    s_mean: "수호",
  },
  {
    month: "3",
    date: "9",
    flower: "낙엽송",
    f_mean: "대담",
    stone: "실버 펄",
    s_mean: "숭배",
  },
  {
    month: "3",
    date: "10",
    flower: "느릅나무",
    f_mean: "고귀함",
    stone: "하울라이트",
    s_mean: "숭고한 상징",
  },
  {
    month: "3",
    date: "11",
    flower: "씀바귀",
    f_mean: "순박함",
    stone: "이네사이트",
    s_mean: "정열",
  },
  {
    month: "3",
    date: "12",
    flower: "수양버들",
    f_mean: "사랑의 슬픔",
    stone: "카야사이트",
    s_mean: "순종",
  },
  {
    month: "3",
    date: "13",
    flower: "산옥잠화",
    f_mean: "사랑의 망각",
    stone: "옐로우 다이아몬드",
    s_mean: "변화하는 평화",
  },
  {
    month: "3",
    date: "14",
    flower: "아몬드",
    f_mean: "희망",
    stone: "컬러리스 스피넬",
    s_mean: "순진",
  },
  {
    month: "3",
    date: "15",
    flower: "독당근",
    f_mean: "죽음도 아깝지 않으리",
    stone: "오렌지 문스톤",
    s_mean: "사랑의 촉진",
  },
  {
    month: "3",
    date: "16",
    flower: "박하",
    f_mean: "미덕",
    stone: "로즈 쿼츠",
    s_mean: "사랑을 전하다",
  },
  {
    month: "3",
    date: "17",
    flower: "콩꽃",
    f_mean: "반드시 오고야 말 행복",
    stone: "다이옵테이스",
    s_mean: "자유로운 삶",
  },
  {
    month: "3",
    date: "18",
    flower: "아스파라거스",
    f_mean: "무변화",
    stone: "카올리나이트",
    s_mean: "배려심",
  },
  {
    month: "3",
    date: "19",
    flower: "치자나무",
    f_mean: "한없는 즐거움",
    stone: "바이컬러 쿼츠",
    s_mean: "봄의 방문",
  },
  {
    month: "3",
    date: "20",
    flower: "보라색 튤립",
    f_mean: "영원한 애정",
    stone: "유클레이스",
    s_mean: "면밀한 조사",
  },
  {
    month: "3",
    date: "21",
    flower: "벚꽃난",
    f_mean: "인생의 출발",
    stone: "아이언",
    s_mean: "강인한 힘",
  },
  {
    month: "3",
    date: "22",
    flower: "당아욱",
    f_mean: "은혜",
    stone: "소그디어나이트",
    s_mean: "생명의 재생",
  },
  {
    month: "3",
    date: "23",
    flower: "글라디올러스",
    f_mean: "정열적인 사랑",
    stone: "픽춰드 재스퍼",
    s_mean: "몽상",
  },
  {
    month: "3",
    date: "24",
    flower: "금영화",
    f_mean: "희망",
    stone: "그린 쿼츠",
    s_mean: "감정을 가라앉히다",
  },
  {
    month: "3",
    date: "25",
    flower: "덩굴",
    f_mean: "아름다움",
    stone: "피치 지르콘",
    s_mean: "고통의 구원",
  },
  {
    month: "3",
    date: "26",
    flower: "흰앵초",
    f_mean: "첫사랑",
    stone: "플래티넘",
    s_mean: "다감한 마음",
  },
  {
    month: "3",
    date: "27",
    flower: "칼세올라리아",
    f_mean: "도움",
    stone: "퍼플 지르콘",
    s_mean: "너무 많은 대화",
  },
  {
    month: "3",
    date: "28",
    flower: "꽃아카시아나무",
    f_mean: "품위",
    stone: "핑크 다이아몬드",
    s_mean: "사랑의 도래",
  },
  {
    month: "3",
    date: "29",
    flower: "우엉",
    f_mean: "괴롭히지 말아요",
    stone: "그린 다이아몬드",
    s_mean: "우아",
  },
  {
    month: "3",
    date: "30",
    flower: "금작화",
    f_mean: "청초",
    stone: "엔젤 스킨 코랄",
    s_mean: "변치 않는 마음",
  },
  {
    month: "3",
    date: "31",
    flower: "흑종초",
    f_mean: "꿈길의 애정",
    stone: "아서클레이스",
    s_mean: "목적 달성",
  },
  {
    month: "4",
    date: "1",
    flower: "아몬드",
    f_mean: "진실한 사랑",
    stone: "하키마 다이아몬드",
    s_mean: "꿈",
  },
  {
    month: "4",
    date: "2",
    flower: "아네모네",
    f_mean: "기대",
    stone: "셀리스타이트",
    s_mean: "영혼의 정화",
  },
  {
    month: "4",
    date: "3",
    flower: "나팔수선화",
    f_mean: "존경",
    stone: "제오라이트",
    s_mean: "재생",
  },
  {
    month: "4",
    date: "4",
    flower: "빨간 아네모네",
    f_mean: "그대를 사랑해",
    stone: "젬실리카",
    s_mean: "행운과 번영",
  },
  {
    month: "4",
    date: "5",
    flower: "무화과",
    f_mean: "풍부",
    stone: "컬러리스 사파이어",
    s_mean: "성스러운 힘과 빛나는 지성",
  },
  {
    month: "4",
    date: "6",
    flower: "아도니스",
    f_mean: "영원한 행복",
    stone: "블루 다이아몬드",
    s_mean: "만전",
  },
  {
    month: "4",
    date: "7",
    flower: "공작고사리",
    f_mean: "신명",
    stone: "블라질리아나이트",
    s_mean: "이지적",
  },
  {
    month: "4",
    date: "8",
    flower: "금작화",
    f_mean: "박애",
    stone: "파파라치아 사파이어",
    s_mean: "빛의 꽃",
  },
  {
    month: "4",
    date: "9",
    flower: "벚나무",
    f_mean: "아름다운 영혼",
    stone: "세라사이트",
    s_mean: "고결함",
  },
  {
    month: "4",
    date: "10",
    flower: "빙카",
    f_mean: "즐거운 추억",
    stone: "화이트 지르콘",
    s_mean: "모든 것을 건 마음",
  },
  {
    month: "4",
    date: "11",
    flower: "꽃고비",
    f_mean: "와 주세요",
    stone: "블루나이트",
    s_mean: "공격적인 느낌",
  },
  {
    month: "4",
    date: "12",
    flower: "복사꽃",
    f_mean: "사랑의 노예",
    stone: "핑크 플로라이트",
    s_mean: "환상적",
  },
  {
    month: "4",
    date: "13",
    flower: "페르시아 국화",
    f_mean: "경쟁심",
    stone: "바이올렛 펄",
    s_mean: "자존심",
  },
  {
    month: "4",
    date: "14",
    flower: "흰나팔꽃",
    f_mean: "넘치는 기쁨",
    stone: "컬러리스 토파즈",
    s_mean: "지성을 가진 천재",
  },
  {
    month: "4",
    date: "15",
    flower: "펜 오키드",
    f_mean: "훌륭함",
    stone: "피콕 그린 펄",
    s_mean: "자연에 대한 사랑",
  },
  {
    month: "4",
    date: "16",
    flower: "튤립",
    f_mean: "아름다운 눈동자",
    stone: "히데나이트",
    s_mean: "청정",
  },
  {
    month: "4",
    date: "17",
    flower: "독일 창포",
    f_mean: "멋진 결혼",
    stone: "그린 스피넬",
    s_mean: "희망과 신앙",
  },
  {
    month: "4",
    date: "18",
    flower: "자운영",
    f_mean: "감화",
    stone: "액서나이트",
    s_mean: "노력의 계속",
  },
  {
    month: "4",
    date: "19",
    flower: "참제비고깔",
    f_mean: "청명",
    stone: "바이올렛 지르콘",
    s_mean: "세속성과 정신성",
  },
  {
    month: "4",
    date: "20",
    flower: "배나무",
    f_mean: "온화한 애정",
    stone: "클로러멜라나이트",
    s_mean: "거짓과 진실",
  },
  {
    month: "4",
    date: "21",
    flower: "수양버들",
    f_mean: "내 가슴의 슬픔",
    stone: "맨덜루사이트",
    s_mean: "사랑과 예감",
  },
  {
    month: "4",
    date: "22",
    flower: "과꽃",
    f_mean: "믿음직한 사랑",
    stone: "애스트로피라이트",
    s_mean: "믿는 사랑",
  },
  {
    month: "4",
    date: "23",
    flower: "도라지",
    f_mean: "상냥하고 따뜻함",
    stone: "디저트 로즈",
    s_mean: "사랑과 지성",
  },
  {
    month: "4",
    date: "24",
    flower: "제라늄",
    f_mean: "결심",
    stone: "쿤차이트",
    s_mean: "연인 도래의 조짐",
  },
  {
    month: "4",
    date: "25",
    flower: "중국 패모",
    f_mean: "위엄",
    stone: "플라즈마",
    s_mean: "양자택일의 결단",
  },
  {
    month: "4",
    date: "26",
    flower: "논냉이",
    f_mean: "불타는 애정",
    stone: "스기라이트",
    s_mean: "영원불변한 사랑",
  },
  {
    month: "4",
    date: "27",
    flower: "수련",
    f_mean: "청순한 마음",
    stone: "카넬리안",
    s_mean: "명석한 사고",
  },
  {
    month: "4",
    date: "28",
    flower: "빨간 앵초",
    f_mean: "비할 바 없는 아름다움",
    stone: "킴버라이트",
    s_mean: "사랑의 수호",
  },
  {
    month: "4",
    date: "29",
    flower: "동백나무",
    f_mean: "매력",
    stone: "로드스톤",
    s_mean: "시종일관",
  },
  {
    month: "4",
    date: "30",
    flower: "금사슬나무",
    f_mean: "슬픈 아름다움",
    stone: "실리마나이트",
    s_mean: "경고",
  },
  {
    month: "5",
    date: "1",
    flower: "구륜 앵초",
    f_mean: "젊은 날의 슬픔",
    stone: "아마조나이트",
    s_mean: "시기가 도래하다",
  },
  {
    month: "5",
    date: "2",
    flower: "미나리아재비",
    f_mean: "천진난만",
    stone: "옐로우 베릴",
    s_mean: "견디는 사랑",
  },
  {
    month: "5",
    date: "3",
    flower: "민들레",
    f_mean: "신탁",
    stone: "그린 지르콘",
    s_mean: "평화의 소원",
  },
  {
    month: "5",
    date: "4",
    flower: "딸기",
    f_mean: "존중과 애정",
    stone: "포스테라이트",
    s_mean: "위대한 힘",
  },
  {
    month: "5",
    date: "5",
    flower: "은방울꽃",
    f_mean: "섬세함",
    stone: "레드 크랄",
    s_mean: "어린 마음",
  },
  {
    month: "5",
    date: "6",
    flower: "비단향나무꽃",
    f_mean: "영원한 아름다움",
    stone: "아이드크레이스",
    s_mean: "약속",
  },
  {
    month: "5",
    date: "7",
    flower: "딸기",
    f_mean: "사랑과 존경",
    stone: "클리다이트",
    s_mean: "마음의 성장",
  },
  {
    month: "5",
    date: "8",
    flower: "수련",
    f_mean: "청순한 마음",
    stone: "에메랄드 캣츠 아이",
    s_mean: "상상력",
  },
  {
    month: "5",
    date: "9",
    flower: "겹벚꽃",
    f_mean: "단아함",
    stone: "블랙 펄",
    s_mean: "조용한 강인함",
  },
  {
    month: "5",
    date: "10",
    flower: "꽃창포",
    f_mean: "우아한 마음",
    stone: "로빈스 에그 블루",
    s_mean: "해방된 마음",
  },
  {
    month: "5",
    date: "11",
    flower: "사과",
    f_mean: "유혹",
    stone: "레이스 아게이트",
    s_mean: "침착한 용기",
  },
  {
    month: "5",
    date: "12",
    flower: "라일락",
    f_mean: "사랑의 싹",
    stone: "카콕서나이트",
    s_mean: "의식의 도달",
  },
  {
    month: "5",
    date: "13",
    flower: "산사나무",
    f_mean: "유일한 사랑",
    stone: "아이보리",
    s_mean: "청순",
  },
  {
    month: "5",
    date: "14",
    flower: "매발톱꽃",
    f_mean: "승리의 맹세",
    stone: "블루 그린 지르콘",
    s_mean: "떠나가는 고통",
  },
  {
    month: "5",
    date: "15",
    flower: "물망초",
    f_mean: "나를 잊지 말아요",
    stone: "레드 제나이트",
    s_mean: "결단력",
  },
  {
    month: "5",
    date: "16",
    flower: "조밥나물",
    f_mean: "선언",
    stone: "텍타이트",
    s_mean: "자유로운 삶",
  },
  {
    month: "5",
    date: "17",
    flower: "튤립",
    f_mean: "사랑의 표시",
    stone: "퍼플 사파이어",
    s_mean: "첫사랑의 추억",
  },
  {
    month: "5",
    date: "18",
    flower: "옥슬립 앵초",
    f_mean: "첫사랑",
    stone: "고제나이트",
    s_mean: "기품",
  },
  {
    month: "5",
    date: "19",
    flower: "아리스타타",
    f_mean: "아름다움의 소유자",
    stone: "노제라이트",
    s_mean: "위기를 극복하다",
  },
  {
    month: "5",
    date: "20",
    flower: "괭이밥",
    f_mean: "빛나는 마음",
    stone: "자라타이트",
    s_mean: "내면의 힘",
  },
  {
    month: "5",
    date: "21",
    flower: "담홍색 참제비고깔",
    f_mean: "자유",
    stone: "오퍼라이즈드 우드",
    s_mean: "융합과 동조",
  },
  {
    month: "5",
    date: "22",
    flower: "귀고리꽃",
    f_mean: "열렬한 마음",
    stone: "덴드리틱 쿼츠",
    s_mean: "만족스러운 성장",
  },
  {
    month: "5",
    date: "23",
    flower: "싹",
    f_mean: "첫사랑의 추억",
    stone: "앤드라다이트",
    s_mean: "충성심",
  },
  {
    month: "5",
    date: "24",
    flower: "헬리오프로프",
    f_mean: "사랑이여 영원하라",
    stone: "아듀라리아",
    s_mean: "계획",
  },
  {
    month: "5",
    date: "25",
    flower: "삼색제비꽃",
    f_mean: "순애",
    stone: "블루 앰버",
    s_mean: "조용히 타오르는 마음",
  },
  {
    month: "5",
    date: "26",
    flower: "올리브나무",
    f_mean: "평화",
    stone: "코퍼",
    s_mean: "사랑의 노예",
  },
  {
    month: "5",
    date: "27",
    flower: "데이지",
    f_mean: "순수한 마음",
    stone: "바데라이트",
    s_mean: "인내",
  },
  {
    month: "5",
    date: "28",
    flower: "박하",
    f_mean: "미덕",
    stone: "화이트 칼세도니",
    s_mean: "우아",
  },
  {
    month: "5",
    date: "29",
    flower: "토끼풀",
    f_mean: "쾌활",
    stone: "잘로스톡",
    s_mean: "행운의 승리",
  },
  {
    month: "5",
    date: "30",
    flower: "보랏빛 라일락",
    f_mean: "사랑의 싹이 트다",
    stone: "차보라이트",
    s_mean: "영향력",
  },
  {
    month: "5",
    date: "31",
    flower: "무릇",
    f_mean: "강한 자제력",
    stone: "스모키 쿼츠",
    s_mean: "안식",
  },
  {
    month: "6",
    date: "1",
    flower: "장미",
    f_mean: "나의 마음 그대만이 아네",
    stone: "컬러체인지 사파이어",
    s_mean: "이면성",
  },
  {
    month: "6",
    date: "2",
    flower: "빨강 매발톱꽃",
    f_mean: "솔직함",
    stone: "클리어 앰버",
    s_mean: "꿈의 실현",
  },
  {
    month: "6",
    date: "3",
    flower: "아마",
    f_mean: "감사",
    stone: "페나사이트",
    s_mean: "기분 일소",
  },
  {
    month: "6",
    date: "4",
    flower: "장미",
    f_mean: "아름답게 빛나는 얼굴",
    stone: "오돈라이트",
    s_mean: "공격과 방어",
  },
  {
    month: "6",
    date: "5",
    flower: "메리골드",
    f_mean: "가련한 애정",
    stone: "알렉산드라이트",
    s_mean: "이면성",
  },
  {
    month: "6",
    date: "6",
    flower: "노란 붓꽃",
    f_mean: "믿는 자의 행복",
    stone: "실리시피어드우드",
    s_mean: "융합과 변화",
  },
  {
    month: "6",
    date: "7",
    flower: "슈미트티아나",
    f_mean: "사모하는 마음",
    stone: "핑크 펄",
    s_mean: "인내심 강한 사랑",
  },
  {
    month: "6",
    date: "8",
    flower: "재스민",
    f_mean: "사랑스러움",
    stone: "새니딘",
    s_mean: "초능력과의 융합",
  },
  {
    month: "6",
    date: "9",
    flower: "스위트피",
    f_mean: "우아한 추억",
    stone: "우렉사이트",
    s_mean: "두뇌 명석",
  },
  {
    month: "6",
    date: "10",
    flower: "수염패랭이꽃",
    f_mean: "의협심",
    stone: "쿼츠",
    s_mean: "조화",
  },
  {
    month: "6",
    date: "11",
    flower: "중국 패모",
    f_mean: "위엄",
    stone: "화이트 래브라도라이트",
    s_mean: "좋은 소문",
  },
  {
    month: "6",
    date: "12",
    flower: "레제다 오도라타",
    f_mean: "매력",
    stone: "마베 펄",
    s_mean: "매력",
  },
  {
    month: "6",
    date: "13",
    flower: "디기탈리스",
    f_mean: "가슴 속의 생각",
    stone: "우바로바이트",
    s_mean: "소심함",
  },
  {
    month: "6",
    date: "14",
    flower: "뚜껑별꽃",
    f_mean: "추상",
    stone: "시프린",
    s_mean: "견식",
  },
  {
    month: "6",
    date: "15",
    flower: "카네이션",
    f_mean: "정열",
    stone: "옐로우 재스퍼",
    s_mean: "여행의 안전",
  },
  {
    month: "6",
    date: "16",
    flower: "월하향",
    f_mean: "위험한 쾌락",
    stone: "블루 오팔",
    s_mean: "상쾌한 애정표현",
  },
  {
    month: "6",
    date: "17",
    flower: "토끼풀",
    f_mean: "감화",
    stone: "넵튜나이트",
    s_mean: "생명의 영속성",
  },
  {
    month: "6",
    date: "18",
    flower: "백리향",
    f_mean: "용기",
    stone: "아르젠타이트",
    s_mean: "사악함으로부터의 방어",
  },
  {
    month: "6",
    date: "19",
    flower: "들장미",
    f_mean: "사랑",
    stone: "블랙스타 사파이어",
    s_mean: "진혼",
  },
  {
    month: "6",
    date: "20",
    flower: "꼬리풀",
    f_mean: "달성",
    stone: "그린 플로라이트",
    s_mean: "숨은 미덕",
  },
  {
    month: "6",
    date: "21",
    flower: "달맞이꽃",
    f_mean: "기다림",
    stone: "서펀틴",
    s_mean: "보호",
  },
  {
    month: "6",
    date: "22",
    flower: "가막살나무",
    f_mean: "사랑은 죽음보다 강하다",
    stone: "선스톤",
    s_mean: "광채",
  },
  {
    month: "6",
    date: "23",
    flower: "접시꽃",
    f_mean: "열렬한 사랑",
    stone: "안욜라이트",
    s_mean: "소극적인 사랑",
  },
  {
    month: "6",
    date: "24",
    flower: "버베나",
    f_mean: "가족의 화합",
    stone: "워터 오팔",
    s_mean: "처녀의 연심",
  },
  {
    month: "6",
    date: "25",
    flower: "나팔꽃",
    f_mean: "덧없는 사랑",
    stone: "말라카이트",
    s_mean: "통찰력과 상상력",
  },
  {
    month: "6",
    date: "26",
    flower: "흰 라일락",
    f_mean: "아름다운 맹세",
    stone: "스페샤르타이트",
    s_mean: "복종하는 마음",
  },
  {
    month: "6",
    date: "27",
    flower: "시계꽃",
    f_mean: "성스러운 사랑",
    stone: "리디코타이트",
    s_mean: "다채로운 매력",
  },
  {
    month: "6",
    date: "28",
    flower: "제라늄",
    f_mean: "그대 있기에 행복이 있네",
    stone: "블루 지르콘",
    s_mean: "환각",
  },
  {
    month: "6",
    date: "29",
    flower: "빨간 제라늄",
    f_mean: "그대가 있어 사랑이 있네",
    stone: "재스퍼",
    s_mean: "자기 제어",
  },
  {
    month: "6",
    date: "30",
    flower: "인동",
    f_mean: "사랑의 인연",
    stone: "유렉사이트 캣츠아이",
    s_mean: "마음의 눈",
  },
  {
    month: "7",
    date: "1",
    flower: "단양쑥부쟁이",
    f_mean: "태만",
    stone: "블러드샷아이오라이트",
    s_mean: "방향의 시사",
  },
  {
    month: "7",
    date: "2",
    flower: "금어초",
    f_mean: "욕망",
    stone: "배리사이트",
    s_mean: "자연의 숙성",
  },
  {
    month: "7",
    date: "3",
    flower: "흰색 양귀비",
    f_mean: "망각",
    stone: "록 크리스탈 ",
    s_mean: "유쾌한 마음",
  },
  {
    month: "7",
    date: "4",
    flower: "자목련",
    f_mean: "존경",
    stone: "다이옵사이드",
    s_mean: "행운으로 가는 이정표",
  },
  {
    month: "7",
    date: "5",
    flower: "라벤더",
    f_mean: "나에게 대답하세요",
    stone: "아나테스",
    s_mean: "미래의 행운",
  },
  {
    month: "7",
    date: "6",
    flower: "해바라기",
    f_mean: "애모",
    stone: "아파치 티어",
    s_mean: "불가사의",
  },
  {
    month: "7",
    date: "7",
    flower: "구스베리",
    f_mean: "예상",
    stone: "스타로드 쿼츠",
    s_mean: "만남",
  },
  {
    month: "7",
    date: "8",
    flower: "버드푸트",
    f_mean: "다시 만날 날까지",
    stone: "밀키 오팔",
    s_mean: "설렘",
  },
  {
    month: "7",
    date: "9",
    flower: "아이비 제라늄",
    f_mean: "진실한 애정",
    stone: "브라운 다이아몬드",
    s_mean: "불굴의 신념",
  },
  {
    month: "7",
    date: "10",
    flower: "초롱꽃",
    f_mean: "감사",
    stone: "스포듀언",
    s_mean: "무한의 사랑",
  },
  {
    month: "7",
    date: "11",
    flower: "아스포델",
    f_mean: "나는 당신의 것",
    stone: "크림 펄",
    s_mean: "새로운 만남",
  },
  {
    month: "7",
    date: "12",
    flower: "좁은입배풍동",
    f_mean: "참을 수 없어",
    stone: "레드 베릴",
    s_mean: "고차원적인 의식",
  },
  {
    month: "7",
    date: "13",
    flower: "잡초꽃",
    f_mean: "현실적인 사람",
    stone: "크리스베릴",
    s_mean: "광채",
  },
  {
    month: "7",
    date: "14",
    flower: "플록스",
    f_mean: "온화",
    stone: "쓰리컬러 플로라이트",
    s_mean: "다면성",
  },
  {
    month: "7",
    date: "15",
    flower: "들장미",
    f_mean: "사랑스러움",
    stone: "거사이트",
    s_mean: "영능력",
  },
  {
    month: "7",
    date: "16",
    flower: "비단향꽃무",
    f_mean: "영원한 아름다움",
    stone: "아이즈라이트",
    s_mean: "명상력",
  },
  {
    month: "7",
    date: "17",
    flower: "흰색장미",
    f_mean: "존경",
    stone: "어벤춰린",
    s_mean: "빛나는 미래",
  },
  {
    month: "7",
    date: "18",
    flower: "이끼 장미",
    f_mean: "가련함",
    stone: "래브라도라이트 펠드스퍼",
    s_mean: "밀회",
  },
  {
    month: "7",
    date: "19",
    flower: "백부자",
    f_mean: "아름답게 빛나다",
    stone: "하이드로 로드크로사이트",
    s_mean: "정의",
  },
  {
    month: "7",
    date: "20",
    flower: "가지",
    f_mean: "진실한 애정",
    stone: "아쿠아마린 캣츠아이",
    s_mean: "광명",
  },
  {
    month: "7",
    date: "21",
    flower: "노랑장미",
    f_mean: "아름다움의 소유자",
    stone: "블루 재스퍼",
    s_mean: "감정의 조정",
  },
  {
    month: "7",
    date: "22",
    flower: "패랭이꽃",
    f_mean: "사모하는 마음",
    stone: "플라워 옵시디언",
    s_mean: "새로운 출발",
  },
  {
    month: "7",
    date: "23",
    flower: "장미",
    f_mean: "아름다움의 소유자",
    stone: "워터메론 토르마린",
    s_mean: "겹치는 행운",
  },
  {
    month: "7",
    date: "24",
    flower: "연령초",
    f_mean: "그윽한 마음",
    stone: "워더라이트",
    s_mean: "독과 정화",
  },
  {
    month: "7",
    date: "25",
    flower: "말오줌나무",
    f_mean: "열심",
    stone: "쉘",
    s_mean: "아름다운 맹세",
  },
  {
    month: "7",
    date: "26",
    flower: "향쑥",
    f_mean: "평화",
    stone: "퍼실 로랄",
    s_mean: "정복",
  },
  {
    month: "7",
    date: "27",
    flower: "제라늄",
    f_mean: "진실한 애정",
    stone: "그레이 다이아몬드",
    s_mean: "조역부터 출발",
  },
  {
    month: "7",
    date: "28",
    flower: "패랭이꽃",
    f_mean: "언제나 사랑",
    stone: "알만다인 스피넬",
    s_mean: "영혼과의 교류",
  },
  {
    month: "7",
    date: "29",
    flower: "선인장",
    f_mean: "불타는 마음",
    stone: "블랙 오팔",
    s_mean: "위협",
  },
  {
    month: "7",
    date: "30",
    flower: "서양종 보리수",
    f_mean: "부부애",
    stone: "에피도트",
    s_mean: "과거로부터의 해방",
  },
  {
    month: "7",
    date: "31",
    flower: "호박",
    f_mean: "광대함",
    stone: "레드 지르콘",
    s_mean: "평안",
  },
  {
    month: "8",
    date: "1",
    flower: "빨강 양귀비",
    f_mean: "위로",
    stone: "시트린",
    s_mean: "달콤한 추억",
  },
  {
    month: "8",
    date: "2",
    flower: "수레국화",
    f_mean: "행복",
    stone: "블루 쿼츠",
    s_mean: "생명의 탄생",
  },
  {
    month: "8",
    date: "3",
    flower: "수박풀",
    f_mean: "순간의 아름다움",
    stone: "크릴스베릴 캣츠 아이",
    s_mean: "황금의 눈동자",
  },
  {
    month: "8",
    date: "4",
    flower: "옥수수",
    f_mean: "보물",
    stone: "마카사이트",
    s_mean: "추억과 동경",
  },
  {
    month: "8",
    date: "5",
    flower: "엘리카",
    f_mean: "고독",
    stone: "캣츠 아이 문스톤",
    s_mean: "사랑의 기회",
  },
  {
    month: "8",
    date: "6",
    flower: "능소화",
    f_mean: "명예",
    stone: "다크그린 지르콘",
    s_mean: "정신의 위안",
  },
  {
    month: "8",
    date: "7",
    flower: "석류",
    f_mean: "원숙한 아름다움",
    stone: "옐로우 애퍼타이트",
    s_mean: "의혹",
  },
  {
    month: "8",
    date: "8",
    flower: "진달래",
    f_mean: "사랑의 희열",
    stone: "루틸",
    s_mean: "사랑의 화살",
  },
  {
    month: "8",
    date: "9",
    flower: "시스터스",
    f_mean: "인기",
    stone: "캐커파이라이트",
    s_mean: "망각의 제거",
  },
  {
    month: "8",
    date: "10",
    flower: "이끼",
    f_mean: "모성애",
    stone: "아이오라이트",
    s_mean: "영적 능력을 높이다",
  },
  {
    month: "8",
    date: "11",
    flower: "빨강무늬 제라늄",
    f_mean: "위안",
    stone: "옐로우 사파이어",
    s_mean: "집중력",
  },
  {
    month: "8",
    date: "12",
    flower: "협죽도",
    f_mean: "위험한 쾌락",
    stone: "칸커 아게이트 ",
    s_mean: "자연의 행방",
  },
  {
    month: "8",
    date: "13",
    flower: "골든 로드",
    f_mean: "경계",
    stone: "옐로우 지르콘",
    s_mean: "출산의 슬픔",
  },
  {
    month: "8",
    date: "14",
    flower: "저먼더",
    f_mean: "경애",
    stone: "파이오 오팔",
    s_mean: "사랑하는 사람",
  },
  {
    month: "8",
    date: "15",
    flower: "해바라기",
    f_mean: "광휘",
    stone: "블루레스 아게이트",
    s_mean: "영혼의 움직임",
  },
  {
    month: "8",
    date: "16",
    flower: "타마린드",
    f_mean: "사치",
    stone: "래브라도라이트",
    s_mean: "사모",
  },
  {
    month: "8",
    date: "17",
    flower: "튤립 나무",
    f_mean: "전원의 행복",
    stone: "파이라이트",
    s_mean: "보호력",
  },
  {
    month: "8",
    date: "18",
    flower: "접시꽃",
    f_mean: "열렬한 사랑",
    stone: "오렌지 펄",
    s_mean: "회복",
  },
  {
    month: "8",
    date: "19",
    flower: "로사 캠피온",
    f_mean: "성실",
    stone: "캘사이트",
    s_mean: "영화와 번영",
  },
  {
    month: "8",
    date: "20",
    flower: "프리지아",
    f_mean: "순결",
    stone: "스타 루비",
    s_mean: "중심",
  },
  {
    month: "8",
    date: "21",
    flower: "짚신나물",
    f_mean: "감사",
    stone: "제트",
    s_mean: "망각의 제거",
  },
  {
    month: "8",
    date: "22",
    flower: "스피리아",
    f_mean: "노력",
    stone: "화이트 코랄",
    s_mean: "정결",
  },
  {
    month: "8",
    date: "23",
    flower: "서양종 보리수",
    f_mean: "부부애",
    stone: "이오스포라이트",
    s_mean: "변치 않는 사랑을 바치다",
  },
  {
    month: "8",
    date: "24",
    flower: "금잔화",
    f_mean: "이별의 슬픔",
    stone: "러버",
    s_mean: "연인",
  },
  {
    month: "8",
    date: "25",
    flower: "안스륨",
    f_mean: "사랑에 번민하는 마음",
    stone: "파이어 아게이트",
    s_mean: "정념",
  },
  {
    month: "8",
    date: "26",
    flower: "하이포시스 오리어",
    f_mean: "빛을 찾다",
    stone: "터콰이즈 블루",
    s_mean: "신성한 사랑",
  },
  {
    month: "8",
    date: "27",
    flower: "고비",
    f_mean: "몽상",
    stone: "아파타이트",
    s_mean: "혼동",
  },
  {
    month: "8",
    date: "28",
    flower: "에린지움",
    f_mean: "비밀스러운 애정",
    stone: "핑크 코랄",
    s_mean: "자비로운 사랑",
  },
  {
    month: "8",
    date: "29",
    flower: "꽃담배",
    f_mean: "그대 있어 외롭지 않네",
    stone: "캑터스 아메시스트",
    s_mean: "변화",
  },
  {
    month: "8",
    date: "30",
    flower: "저먼더",
    f_mean: "담백",
    stone: "레인보우 옵시디언",
    s_mean: "각양각색",
  },
  {
    month: "8",
    date: "31",
    flower: "토끼풀",
    f_mean: "약속",
    stone: "모스 아게이트",
    s_mean: "마음의 영양",
  },
  {
    month: "9",
    date: "1",
    flower: "호랑이꽃",
    f_mean: "나를 사랑해 주세요",
    stone: "덴더나이트",
    s_mean: "긍지 높은 사람",
  },
  {
    month: "9",
    date: "2",
    flower: "멕시칸 아이비",
    f_mean: "변화",
    stone: "그레이 펄",
    s_mean: "쟁취하는 사랑",
  },
  {
    month: "9",
    date: "3",
    flower: "마거리트",
    f_mean: "마음 속에 감춘 사랑",
    stone: "레드 다이아몬드",
    s_mean: "탄생의 비밀",
  },
  {
    month: "9",
    date: "4",
    flower: "뱀무",
    f_mean: "만족된 사랑",
    stone: "스핀",
    s_mean: "우주적 의사 소통",
  },
  {
    month: "9",
    date: "5",
    flower: "느릅나무",
    f_mean: "신뢰",
    stone: "골든 펄",
    s_mean: "성숙",
  },
  {
    month: "9",
    date: "6",
    flower: "한련",
    f_mean: "애국심",
    stone: "조아사이트",
    s_mean: "영력의 상징",
  },
  {
    month: "9",
    date: "7",
    flower: "오렌지",
    f_mean: "순결",
    stone: "히아신스",
    s_mean: "안심",
  },
  {
    month: "9",
    date: "8",
    flower: "머스타드",
    f_mean: "무관심",
    stone: "아코아펄",
    s_mean: "품격",
  },
  {
    month: "9",
    date: "9",
    flower: "갓개매취",
    f_mean: "추억",
    stone: "아라고나이트",
    s_mean: "능력의 발휘",
  },
  {
    month: "9",
    date: "10",
    flower: "흰색 과꽃",
    f_mean: "믿는 마음",
    stone: "댄버라이트",
    s_mean: "폭 넓은 지성",
  },
  {
    month: "9",
    date: "11",
    flower: "알로에",
    f_mean: "양극단을 극복하는 불굴의 의지",
    stone: "레인보우 플로라이트",
    s_mean: "소원 성취",
  },
  {
    month: "9",
    date: "12",
    flower: "클레마티스",
    f_mean: "마음의 아름다움",
    stone: "파이어라이트",
    s_mean: "운명적 인연",
  },
  {
    month: "9",
    date: "13",
    flower: "버드나무",
    f_mean: "솔직",
    stone: "골든 베릴",
    s_mean: "찬란했던 좋은 날",
  },
  {
    month: "9",
    date: "14",
    flower: "마르멜로",
    f_mean: "유혹",
    stone: "아이언 로즈",
    s_mean: "구원의 힘",
  },
  {
    month: "9",
    date: "15",
    flower: "달리아",
    f_mean: "화려함",
    stone: "파라이바 토르마린",
    s_mean: "원점 회귀",
  },
  {
    month: "9",
    date: "16",
    flower: "용담",
    f_mean: "슬픈 그대가 좋아요",
    stone: "프레나이트",
    s_mean: "건강한 아름다움",
  },
  {
    month: "9",
    date: "17",
    flower: "에리카",
    f_mean: "고독",
    stone: "다이옵테이스",
    s_mean: "재회",
  },
  {
    month: "9",
    date: "18",
    flower: "엉겅퀴",
    f_mean: "엄격",
    stone: "만다린 가넷",
    s_mean: "유복",
  },
  {
    month: "9",
    date: "19",
    flower: "사초",
    f_mean: "자중",
    stone: "래쥴라이트",
    s_mean: "명상력",
  },
  {
    month: "9",
    date: "20",
    flower: "로즈마리",
    f_mean: "나를 생각해요",
    stone: "블루 스피넬",
    s_mean: "사랑의 자극",
  },
  {
    month: "9",
    date: "21",
    flower: "사프란",
    f_mean: "후회스러운 청춘",
    stone: "세레나이트",
    s_mean: "자기의식",
  },
  {
    month: "9",
    date: "22",
    flower: "퀘이킹 그라스",
    f_mean: "흥분",
    stone: "지르콘",
    s_mean: "순수",
  },
  {
    month: "9",
    date: "23",
    flower: "주목",
    f_mean: "고상함",
    stone: "아메트린",
    s_mean: "빛과 그림자",
  },
  {
    month: "9",
    date: "24",
    flower: "오렌지",
    f_mean: "순결",
    stone: "디맨토이드",
    s_mean: "질주",
  },
  {
    month: "9",
    date: "25",
    flower: "메귀리",
    f_mean: "위로",
    stone: "바이컬러 토르마린",
    s_mean: "대칭과 조화",
  },
  {
    month: "9",
    date: "26",
    flower: "감",
    f_mean: "자애",
    stone: "오렌지 다이아몬드",
    s_mean: "약속된 사랑",
  },
  {
    month: "9",
    date: "27",
    flower: "떡갈나무",
    f_mean: "사랑은 영원히",
    stone: "트라피체 사파이어",
    s_mean: "자유로운 삶",
  },
  {
    month: "9",
    date: "28",
    flower: "색비름",
    f_mean: "애정",
    stone: "아메시스트 쿼츠",
    s_mean: "냉정한 사고",
  },
  {
    month: "9",
    date: "29",
    flower: "사과",
    f_mean: "명성",
    stone: "임페리얼 토파즈",
    s_mean: "탁월한 힘",
  },
  {
    month: "9",
    date: "30",
    flower: "삼나무",
    f_mean: "웅대",
    stone: "블루스타 사파이어",
    s_mean: "지식의 인도",
  },
  {
    month: "10",
    date: "1",
    flower: "빨강 국화",
    f_mean: "사랑",
    stone: "엘바이트",
    s_mean: "재현",
  },
  {
    month: "10",
    date: "2",
    flower: "살구",
    f_mean: "수줍음",
    stone: "하이 쿼츠",
    s_mean: "달성",
  },
  {
    month: "10",
    date: "3",
    flower: "단풍나무",
    f_mean: "자제",
    stone: "바이올렛 다이아몬드",
    s_mean: "매력적인 관계",
  },
  {
    month: "10",
    date: "4",
    flower: "홉",
    f_mean: "순진무구",
    stone: "오팔 재스퍼",
    s_mean: "정확한 간격",
  },
  {
    month: "10",
    date: "5",
    flower: "종려나무",
    f_mean: "승리",
    stone: "라리마",
    s_mean: "조용한 관찰",
  },
  {
    month: "10",
    date: "6",
    flower: "개암나무",
    f_mean: "화해",
    stone: "크리소프레이즈",
    s_mean: "풍요",
  },
  {
    month: "10",
    date: "7",
    flower: "전나무",
    f_mean: "고상함",
    stone: "로드나이트",
    s_mean: "자신을 높임",
  },
  {
    month: "10",
    date: "8",
    flower: "파슬리",
    f_mean: "승리",
    stone: "블루 칼세도니",
    s_mean: "추억",
  },
  {
    month: "10",
    date: "9",
    flower: "희향",
    f_mean: "극찬",
    stone: "블루 오닉스",
    s_mean: "좋은 소식",
  },
  {
    month: "10",
    date: "10",
    flower: "멜론",
    f_mean: "포식",
    stone: "토르마린 캣츠 아이",
    s_mean: "개안",
  },
  {
    month: "10",
    date: "11",
    flower: "부처꽃",
    f_mean: "사랑의 슬픔",
    stone: "로드라이트",
    s_mean: "사랑의 행도역",
  },
  {
    month: "10",
    date: "12",
    flower: "월귤",
    f_mean: "반항심",
    stone: "파티컬러드 사파이어",
    s_mean: "증오의 완화",
  },
  {
    month: "10",
    date: "13",
    flower: "조팝나무",
    f_mean: "단정한 사랑",
    stone: "헤마타이트",
    s_mean: "승리의 인도",
  },
  {
    month: "10",
    date: "14",
    flower: "흰색 국화",
    f_mean: "진실",
    stone: "트라피체 에메랄드",
    s_mean: "회전",
  },
  {
    month: "10",
    date: "15",
    flower: "스위트 바즐",
    f_mean: "좋은 희망",
    stone: "어벤춰린 쿼츠",
    s_mean: "사랑의 기회",
  },
  {
    month: "10",
    date: "16",
    flower: "이끼 장미",
    f_mean: "순진무구",
    stone: "화이트 오닉스",
    s_mean: "성공",
  },
  {
    month: "10",
    date: "17",
    flower: "포도",
    f_mean: "신뢰",
    stone: "마그네타이트",
    s_mean: "두려움을 없애다",
  },
  {
    month: "10",
    date: "18",
    flower: "크랜베리",
    f_mean: "마음의 고통을 위로하다",
    stone: "블루 아게이트",
    s_mean: "예술성",
  },
  {
    month: "10",
    date: "19",
    flower: "빨강 봉선화",
    f_mean: "날 건드리지 마세요",
    stone: "스카라베",
    s_mean: "부활",
  },
  {
    month: "10",
    date: "20",
    flower: "마",
    f_mean: "운명",
    stone: "캘커시더라이트",
    s_mean: "소원 성취",
  },
  {
    month: "10",
    date: "21",
    flower: "엉겅퀴",
    f_mean: "독립",
    stone: "쇼울",
    s_mean: "사랑의 충전",
  },
  {
    month: "10",
    date: "22",
    flower: "벗풀",
    f_mean: "신뢰",
    stone: "레피도라이트",
    s_mean: "변혁",
  },
  {
    month: "10",
    date: "23",
    flower: "흰독말풀",
    f_mean: "경애",
    stone: "튤라이트",
    s_mean: "신비",
  },
  {
    month: "10",
    date: "24",
    flower: "매화",
    f_mean: "고결한 마음",
    stone: "인디고라이트",
    s_mean: "예술적 감각",
  },
  {
    month: "10",
    date: "25",
    flower: "단풍나무",
    f_mean: "염려",
    stone: "레드 스피넬",
    s_mean: "호기심",
  },
  {
    month: "10",
    date: "26",
    flower: "수영",
    f_mean: "애정",
    stone: "타이거 아이 쿼츠",
    s_mean: "꿰뚫어 보는 능력",
  },
  {
    month: "10",
    date: "27",
    flower: "들장미",
    f_mean: "시",
    stone: "오우윈",
    s_mean: "성스러운 업적",
  },
  {
    month: "10",
    date: "28",
    flower: "무궁화",
    f_mean: "미묘한 아름다움",
    stone: "콘플라워 블루 사파이어",
    s_mean: "완전한 직선",
  },
  {
    month: "10",
    date: "29",
    flower: "해당화",
    f_mean: "이끄시는 대로",
    stone: "메이트릭스 터콰이즈",
    s_mean: "통찰력과 상상",
  },
  {
    month: "10",
    date: "30",
    flower: "로벨리아",
    f_mean: "악의",
    stone: "핀파이어 오팔",
    s_mean: "올바른 방향성",
  },
  {
    month: "10",
    date: "31",
    flower: "칼라",
    f_mean: "열혈",
    stone: "호크 아이",
    s_mean: "결단과 전진",
  },
  {
    month: "11",
    date: "1",
    flower: "서양모과",
    f_mean: "유일한 사랑",
    stone: "시나몬 스톤",
    s_mean: "성공의 기회",
  },
  {
    month: "11",
    date: "2",
    flower: "루피너스",
    f_mean: "모성애",
    stone: "블랙 오닉스",
    s_mean: "종교적 사색",
  },
  {
    month: "11",
    date: "3",
    flower: "브리오니아",
    f_mean: "거절",
    stone: "골든 사파이어",
    s_mean: "빛나는 매력과 광명",
  },
  {
    month: "11",
    date: "4",
    flower: "골고사리",
    f_mean: "진실의 위안",
    stone: "셉터 쿼츠",
    s_mean: "탄생의 기쁨",
  },
  {
    month: "11",
    date: "5",
    flower: "단양쑥부쟁이",
    f_mean: "공훈",
    stone: "네프라이트",
    s_mean: "시선의 매력",
  },
  {
    month: "11",
    date: "6",
    flower: "등골나물",
    f_mean: "주저",
    stone: "스패러라이트",
    s_mean: "조화와 중용",
  },
  {
    month: "11",
    date: "7",
    flower: "메리골드",
    f_mean: "이별의 슬픔",
    stone: "피트 앰버",
    s_mean: "포용",
  },
  {
    month: "11",
    date: "8",
    flower: "가는동자꽃",
    f_mean: "기지",
    stone: "레드 토파즈",
    s_mean: "생명과 번영",
  },
  {
    month: "11",
    date: "9",
    flower: "몰약의 꽃",
    f_mean: "진실",
    stone: "토터스 쉘",
    s_mean: "장수",
  },
  {
    month: "11",
    date: "10",
    flower: "부용",
    f_mean: "섬세한 아름다움",
    stone: "퍼실",
    s_mean: "선조의 가호",
  },
  {
    month: "11",
    date: "11",
    flower: "흰동백",
    f_mean: "비밀스러운 사랑",
    stone: "블랙 다이아몬드",
    s_mean: "행복의 시작",
  },
  {
    month: "11",
    date: "12",
    flower: "레몬",
    f_mean: "진심으로 사모함",
    stone: "바이올렛 사파이어",
    s_mean: "화려한 변신",
  },
  {
    month: "11",
    date: "13",
    flower: "레몬 버베나",
    f_mean: "인내",
    stone: "크리스탈 오팔",
    s_mean: "내면의 충실함",
  },
  {
    month: "11",
    date: "14",
    flower: "소나무",
    f_mean: "불로장생",
    stone: "라벤더 제이드",
    s_mean: "약간의 소문",
  },
  {
    month: "11",
    date: "15",
    flower: "황금싸리",
    f_mean: "겸손",
    stone: "크림슨 코랄",
    s_mean: "관용과 냉정한 애정",
  },
  {
    month: "11",
    date: "16",
    flower: "크리스마스 로즈",
    f_mean: "추억",
    stone: "암모나이트",
    s_mean: "가변하는 사고",
  },
  {
    month: "11",
    date: "17",
    flower: "머위",
    f_mean: "공평",
    stone: "그린 루틸 쿼츠",
    s_mean: "기회를 잡다",
  },
  {
    month: "11",
    date: "18",
    flower: "산나리",
    f_mean: "장엄",
    stone: "암소피라이트",
    s_mean: "관용",
  },
  {
    month: "11",
    date: "19",
    flower: "범의귀",
    f_mean: "비밀",
    stone: "블루 토파즈",
    s_mean: "교양과 학문",
  },
  {
    month: "11",
    date: "20",
    flower: "뷰글라스",
    f_mean: "진실",
    stone: "헤소나이트",
    s_mean: "자기 암시의 힘",
  },
  {
    month: "11",
    date: "21",
    flower: "초롱꽃",
    f_mean: "성실",
    stone: "화이트 제다이트",
    s_mean: "정화된 영혼",
  },
  {
    month: "11",
    date: "22",
    flower: "매자나무",
    f_mean: "까다로움",
    stone: "옐로우 오팔",
    s_mean: "숨은 본능",
  },
  {
    month: "11",
    date: "23",
    flower: "양치",
    f_mean: "성실",
    stone: "케시 펄",
    s_mean: "일시적인 휴식",
  },
  {
    month: "11",
    date: "24",
    flower: "가막살나무",
    f_mean: "사랑은 죽음보다 강하다",
    stone: "코발트 캘사이트",
    s_mean: "초조감의 해방",
  },
  {
    month: "11",
    date: "25",
    flower: "개옻나무",
    f_mean: "현명",
    stone: "레드 앰버",
    s_mean: "소악마의 매력",
  },
  {
    month: "11",
    date: "26",
    flower: "서양톱풀",
    f_mean: "지도",
    stone: "스캐포라이트",
    s_mean: "미래 지향",
  },
  {
    month: "11",
    date: "27",
    flower: "붉나무",
    f_mean: "신앙",
    stone: "페트리파이드 우드",
    s_mean: "융합",
  },
  {
    month: "11",
    date: "28",
    flower: "과꽃",
    f_mean: "추상",
    stone: "오렌지슈 브랑누 토파즈",
    s_mean: "보호력",
  },
  {
    month: "11",
    date: "29",
    flower: "바카리스",
    f_mean: "개척",
    stone: "알랙잰드라이프 토르마린",
    s_mean: "사랑과 성",
  },
  {
    month: "11",
    date: "30",
    flower: "낙엽 마른 풀",
    f_mean: "새 봄을 기다림",
    stone: "스타 엔스테타이트",
    s_mean: "깊은 신뢰",
  },
  {
    month: "12",
    date: "1",
    flower: "쑥국화",
    f_mean: "평화",
    stone: "아이언 오팔",
    s_mean: "배려있는 행동",
  },
  {
    month: "12",
    date: "2",
    flower: "이끼",
    f_mean: "모성애",
    stone: "블랙 코랄",
    s_mean: "냉정한 기치",
  },
  {
    month: "12",
    date: "3",
    flower: "라벤더",
    f_mean: "기대",
    stone: "메테오라이트",
    s_mean: "영혼의 재래",
  },
  {
    month: "12",
    date: "4",
    flower: "수영",
    f_mean: "애정",
    stone: "소더라이트",
    s_mean: "잠재의식과 현재의식",
  },
  {
    month: "12",
    date: "5",
    flower: "암브로시아",
    f_mean: "행복한 연애",
    stone: "엔젤라이트",
    s_mean: "빛나는 진리",
  },
  {
    month: "12",
    date: "6",
    flower: "바위취",
    f_mean: "절실한 사랑",
    stone: "엔스테타이트",
    s_mean: "순수한 정의감",
  },
  {
    month: "12",
    date: "7",
    flower: "양치",
    f_mean: "신뢰",
    stone: "짚섬",
    s_mean: "풍요로운 대지",
  },
  {
    month: "12",
    date: "8",
    flower: "갈대",
    f_mean: "깊은 애정",
    stone: "루벨라이트",
    s_mean: "적극적인 행동",
  },
  {
    month: "12",
    date: "9",
    flower: "국화",
    f_mean: "고결한 마음",
    stone: "애러배스터",
    s_mean: "승리를 가져오다",
  },
  {
    month: "12",
    date: "10",
    flower: "빨강 동백",
    f_mean: "고결한 이성",
    stone: "블루 존 플로라이트",
    s_mean: "선조의 가호",
  },
  {
    month: "12",
    date: "11",
    flower: "단양 쑥부쟁이",
    f_mean: "애국심",
    stone: "캐시터라이트",
    s_mean: "치밀한 계획",
  },
  {
    month: "12",
    date: "12",
    flower: "목화",
    f_mean: "우수",
    stone: "소프트핑크 지르콘",
    s_mean: "묘약",
  },
  {
    month: "12",
    date: "13",
    flower: "자홍색 국화",
    f_mean: "사랑",
    stone: "애퍼피라이트",
    s_mean: "영적인 통찰력",
  },
  {
    month: "12",
    date: "14",
    flower: "소나무",
    f_mean: "용감",
    stone: "핑크 사파이어",
    s_mean: "가련함",
  },
  {
    month: "12",
    date: "15",
    flower: "서향",
    f_mean: "불멸",
    stone: "트라피체 루비",
    s_mean: "변신과 도전",
  },
  {
    month: "12",
    date: "16",
    flower: "오리나무",
    f_mean: "장엄",
    stone: "아쥬르말라카이트",
    s_mean: "협조성",
  },
  {
    month: "12",
    date: "17",
    flower: "벚꽃난",
    f_mean: "동감",
    stone: "스펙트로파이트",
    s_mean: "정열적이고 위험한 사랑",
  },
  {
    month: "12",
    date: "18",
    flower: "세이지",
    f_mean: "가정의 덕",
    stone: "토르마린 레이티드 쿼츠",
    s_mean: "대립의 결함",
  },
  {
    month: "12",
    date: "19",
    flower: "스노우 플레이크",
    f_mean: "아름다움",
    stone: "화이트 오팔",
    s_mean: "신의 수호",
  },
  {
    month: "12",
    date: "20",
    flower: "파인애플",
    f_mean: "완전무결",
    stone: "헤미몰파이트",
    s_mean: "쌍극",
  },
  {
    month: "12",
    date: "21",
    flower: "박하",
    f_mean: "덕",
    stone: "블랙 문스톤",
    s_mean: "두 사람의 출발",
  },
  {
    month: "12",
    date: "22",
    flower: "백일홍",
    f_mean: "행복",
    stone: "우바이트",
    s_mean: "넓은 사고",
  },
  {
    month: "12",
    date: "23",
    flower: "플라타너스",
    f_mean: "천재",
    stone: "오렌지 제이드",
    s_mean: "따뜻한 고백",
  },
  {
    month: "12",
    date: "24",
    flower: "겨우살이",
    f_mean: "강한 인내심",
    stone: "스토러라이트",
    s_mean: "강한 보호력",
  },
  {
    month: "12",
    date: "25",
    flower: "서양호랑가시나무",
    f_mean: "선견지명",
    stone: "크로스스톤",
    s_mean: "성스러운 계약",
  },
  {
    month: "12",
    date: "26",
    flower: "크리스마스 로즈",
    f_mean: "추억",
    stone: "퍼플 다이아몬드",
    s_mean: "숨은 비밀",
  },
  {
    month: "12",
    date: "27",
    flower: "매화",
    f_mean: "고결한 마음",
    stone: "몰다바이트",
    s_mean: "애정의 증거",
  },
  {
    month: "12",
    date: "28",
    flower: "석류",
    f_mean: "원숙한 아름다움",
    stone: "로드크로사이트",
    s_mean: "새로운 사랑을 부르다",
  },
  {
    month: "12",
    date: "29",
    flower: "꽈리",
    f_mean: "거짓",
    stone: "파우스타이트",
    s_mean: "부활",
  },
  {
    month: "12",
    date: "30",
    flower: "납매",
    f_mean: "자애",
    stone: "커스머클러",
    s_mean: "자연의 지식",
  },
  {
    month: "12",
    date: "31",
    flower: "노송나무",
    f_mean: "불멸",
    stone: "야호이트",
    s_mean: "온갖 정화",
  },
];

export default BIRTHDAY_DATA;
