// 중앙 집중형 색상 임계값 설정
export const COLOR_THRESHOLDS = {
  BLACK_LIGHTNESS: 12,
  WHITE_LIGHTNESS: 95,
  WHITE_SATURATION: 10,
  SILVER_SATURATION: 5,

  BROWN_HUE_MIN: 20,
  BROWN_HUE_MAX: 60,
  BROWN_DARK_LIGHTNESS: 45,
  BROWN_LIGHT_MIN: 45,
  BROWN_LIGHT_MAX: 80,
  BROWN_SATURATION_MAX: 60,
};

export const HUE_THRESHOLDS = {
  RED_WRAP_MIN: 345,
  RED_WRAP_MAX: 15,
  ORANGE_MIN: 15,
  ORANGE_MAX: 42,
  YELLOW_MIN: 42,
  YELLOW_MAX: 75,
  GREEN_MIN: 75,
  GREEN_MAX: 170,
  SKYBLUE_MIN: 170,
  SKYBLUE_MAX: 210,
  BLUE_MIN: 210,
  BLUE_MAX: 265,
  PURPLE_MIN: 265,
  PURPLE_MAX: 300,
  PINK_MIN: 300,
  PINK_MAX: 345,
};

export type ColorThresholds = typeof COLOR_THRESHOLDS;
export type HueThresholds = typeof HUE_THRESHOLDS;
